require:
  - rubocop-capybara
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - config/**/*

Metrics/MethodLength:
  Max: 20

Minitest/MultipleAssertions:
  Enabled: false

Style/Documentation:
  Enabled: false